from .console import Console
from .debugger import Debugger
from .heapprofiler import HeapProfiler
from .profiler import Profiler
from .runtime import Runtime
from .schema import Schema
from .accessibility import Accessibility
from .animation import Animation
from .applicationcache import ApplicationCache
from .audits import Audits
from .browser import Browser
from .css import CSS
from .cachestorage import CacheStorage
from .dom import DOM
from .domdebugger import DOMDebugger
from .domsnapshot import DOMSnapshot
from .domstorage import DOMStorage
from .database import Database
from .deviceorientation import DeviceOrientation
from .emulation import Emulation
from .headlessexperimental import HeadlessExperimental
from .io import IO
from .indexeddb import IndexedDB
from .input import Input
from .inspector import Inspector
from .layertree import LayerTree
from .log import Log
from .memory import Memory
from .network import Network
from .overlay import Overlay
from .page import Page
from .performance import Performance
from .security import Security
from .serviceworker import ServiceWorker
from .storage import Storage
from .systeminfo import SystemInfo
from .target import Target
from .tethering import Tethering
from .tracing import Tracing

__all__ = ["ProtocolMixin"]


class ProtocolMixin(object):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.Console: Console = Console(self)
        self.Debugger: Debugger = Debugger(self)
        self.HeapProfiler: HeapProfiler = HeapProfiler(self)
        self.Profiler: Profiler = Profiler(self)
        self.Runtime: Runtime = Runtime(self)
        self.Schema: Schema = Schema(self)
        self.Accessibility: Accessibility = Accessibility(self)
        self.Animation: Animation = Animation(self)
        self.ApplicationCache: ApplicationCache = ApplicationCache(self)
        self.Audits: Audits = Audits(self)
        self.Browser: Browser = Browser(self)
        self.CSS: CSS = CSS(self)
        self.CacheStorage: CacheStorage = CacheStorage(self)
        self.DOM: DOM = DOM(self)
        self.DOMDebugger: DOMDebugger = DOMDebugger(self)
        self.DOMSnapshot: DOMSnapshot = DOMSnapshot(self)
        self.DOMStorage: DOMStorage = DOMStorage(self)
        self.Database: Database = Database(self)
        self.DeviceOrientation: DeviceOrientation = DeviceOrientation(self)
        self.Emulation: Emulation = Emulation(self)
        self.HeadlessExperimental: HeadlessExperimental = HeadlessExperimental(self)
        self.IO: IO = IO(self)
        self.IndexedDB: IndexedDB = IndexedDB(self)
        self.Input: Input = Input(self)
        self.Inspector: Inspector = Inspector(self)
        self.LayerTree: LayerTree = LayerTree(self)
        self.Log: Log = Log(self)
        self.Memory: Memory = Memory(self)
        self.Network: Network = Network(self)
        self.Overlay: Overlay = Overlay(self)
        self.Page: Page = Page(self)
        self.Performance: Performance = Performance(self)
        self.Security: Security = Security(self)
        self.ServiceWorker: ServiceWorker = ServiceWorker(self)
        self.Storage: Storage = Storage(self)
        self.SystemInfo: SystemInfo = SystemInfo(self)
        self.Target: Target = Target(self)
        self.Tethering: Tethering = Tethering(self)
        self.Tracing: Tracing = Tracing(self)
